export const FETCHING_LOCKS_SUCCESS = 'FETCHING_LOCKS_SUCCESS';
export const FETCHING_LOCKS_IN_PROGRESS = 'FETCHING_LOCKS_IN_PROGRESS';
export const FETCHING_LOCKS_FAILED = 'FETCHING_LOCKS_FAILED';

export const ADD_TO_UNLOCK_QUEUE = 'ADD_TO_UNLOCK_QUEUE';
export const REMOVE_FROM_UNLOCK_QUEUE = 'REMOVE_FROM_UNLOCK_QUEUE';

export const UPDATE_LOCK_ITEM = 'UPDATE_LOCK_ITEM';
